# Generated by Django 6.0.6 on 2026-06-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='target_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='target_faculty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
