# Generated by Django 6.0.6 on 2026-07-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('cultural', 'Cultural'), ('sports', 'Sports'), ('social', 'Social'), ('technology', 'Technology')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('cancelled', 'Cancelled')], default='published', max_length=20),
        ),
    ]
