# Generated by Django 6.0 on 2026-09-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_event_category_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_otp_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
