# Generated by Django 6.0 on 2026-09-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_password_reset_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_reset_otp',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
