# Generated by Django 6.0.6 on 2026-10-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reminder_type',
            field=models.CharField(choices=[('24h', '24-Hour Reminder'), ('2h', '2-Hour Reminder'), ('30m', '30-Minute Reminder'), ('announcement', 'Announcement'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('push', 'Push'), ('email', 'Email'), ('both', 'Both')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('user', 'event', 'reminder_type')},
        ),
    ]
